export interface Theme {
	id: string
	bg: string
	task: string
	column: string
	text: string
	taskText?: string
	columnText?: string
	reminder?: string
}

// Fallback de invitado: subconjunto del catálogo. El catálogo completo vive en
// la DB (seeded desde prisma/seed.ts) y lo consumen los usuarios logueados.
// `retro` y `prado oscuro` son los defaults FK.
export const themesList: readonly Theme[] = Object.freeze([
	{
		id: 'orange',
		bg: 'bg-orange-400',
		text: 'text-black',
		column: 'bg-orange-100',
		task: 'bg-orange-300',
		reminder: 'bg-orange-200',
	},
	{
		id: 'amber',
		bg: 'bg-[#FAC335]',
		text: 'text-black',
		column: 'bg-amber-100',
		task: 'bg-amber-300',
		reminder: 'bg-amber-200',
	},
	{
		id: 'lime',
		bg: 'bg-lime-400',
		text: 'text-black',
		column: 'bg-lime-100',
		task: 'bg-lime-300',
		reminder: 'bg-lime-200',
	},
	{
		id: 'green',
		bg: 'bg-green-400',
		text: 'text-black',
		column: 'bg-green-100',
		task: 'bg-green-300',
		reminder: 'bg-green-200',
	},
	{
		id: 'teal',
		bg: 'bg-teal-400',
		text: 'text-black',
		column: 'bg-teal-100',
		task: 'bg-teal-300',
		reminder: 'bg-teal-200',
	},
	{
		id: 'blue',
		bg: 'bg-blue-400',
		text: 'text-black',
		column: 'bg-blue-100',
		task: 'bg-blue-300',
		reminder: 'bg-blue-200',
	},
	{
		id: 'indigo',
		bg: 'bg-indigo-400',
		text: 'text-black',
		column: 'bg-indigo-100',
		task: 'bg-indigo-300',
		reminder: 'bg-indigo-200',
	},
	{
		id: 'violet',
		bg: 'bg-violet-400',
		text: 'text-black',
		column: 'bg-violet-100',
		task: 'bg-violet-300',
		reminder: 'bg-violet-200',
	},
	{
		id: 'fuchsia',
		bg: 'bg-fuchsia-400',
		text: 'text-black',
		column: 'bg-fuchsia-100',
		task: 'bg-fuchsia-300',
		reminder: 'bg-fuchsia-200',
	},
	{
		id: 'rose',
		bg: 'bg-rose-400',
		text: 'text-black',
		column: 'bg-rose-100',
		task: 'bg-rose-300',
		reminder: 'bg-rose-200',
	},
	{
		id: 'slate',
		bg: 'bg-slate-400',
		text: 'text-black',
		column: 'bg-slate-100',
		task: 'bg-stone-300',
		reminder: 'bg-slate-200',
	},
	{
		id: 'stone',
		bg: 'bg-stone-400',
		text: 'text-black',
		column: 'bg-stone-100',
		task: 'bg-slate-300',
		reminder: 'bg-stone-200',
	},
	{
		id: 'stone-red-accent',
		bg: 'bg-stone-400',
		text: 'text-black',
		column: 'bg-stone-100',
		task: 'bg-red-300',
		reminder: 'bg-stone-200',
	},
	{
		id: 'BMO',
		bg: 'bg-[#317B71]',
		text: 'text-black',
		column: 'bg-[#ECFDEDC9]',
		task: 'bg-[#FDEF63]',
		reminder: 'bg-[#FDEF63]',
	},
	{
		id: 'fen',
		bg: 'bg-[#AB214F]',
		text: 'text-black',
		column: 'bg-[#FFD7DC]',
		task: 'bg-[#FF8F9F]',
		reminder: 'bg-[#FF8F9F]',
	},
	{
		id: 'matcha mori',
		bg: 'bg-[#7DA14A]',
		text: 'text-[#FFF1C1]',
		column: 'bg-[#FFF2C9]',
		columnText: 'text-black',
		task: 'bg-[#C3C96F]',
		taskText: 'text-black',
		reminder: 'bg-[#8CC13D]',
	},
	{
		id: 'dream',
		bg: 'bg-[#F3E1A8]',
		text: 'text-[#3E36C4]',
		column: 'bg-[#E8E6F8]',
		columnText: 'text-[#3E36C4]',
		task: 'bg-[#9F99DF]',
		taskText: 'text-[#241F5C]',
		reminder: 'bg-[#8F8AD6]',
	},
	{
		id: 'nube lila',
		bg: 'bg-[#596CAD]',
		text: 'text-white',
		column: 'bg-[#EEEAF3]',
		columnText: 'text-black',
		task: 'bg-[#DCB0C3]',
		taskText: 'text-black',
		reminder: 'bg-[#9384B6]',
	},
	{
		id: 'brisa',
		bg: 'bg-gradient-to-t from-[#c1dfc4] to-[#deecdd]',
		text: 'text-[#2F4A3A]',
		column: 'bg-[#FBFDFB]',
		columnText: 'text-black',
		task: 'bg-[#A7CDB0]',
		taskText: 'text-black',
		reminder: 'bg-[#E6D9A8]',
	},
	{
		id: 'algodon',
		bg: 'bg-gradient-to-t from-[#fad0c4] to-[#ffd1ff]',
		text: 'text-[#5A3A4A]',
		column: 'bg-[#FFF5FB]',
		columnText: 'text-black',
		task: 'bg-[#F7B8D0]',
		taskText: 'text-black',
		reminder: 'bg-[#FAD0C4]',
	},
	{
		id: 'amanecer',
		bg: 'bg-gradient-to-b from-[#050608] via-[#3A4166] to-[#F3EFE8]',
		text: 'text-white',
		column: 'bg-[#F3EFE8E0]',
		columnText: 'text-[#1B2036]',
		task: 'bg-[#9BA4C0]',
		taskText: 'text-[#1B2036]',
		reminder: 'bg-[#A9A29A]',
	},
	{
		id: 'aurora',
		bg: 'bg-[radial-gradient(ellipse_420%_80%_at_50%_98%,#FDFBE8_0%,#FBF388_5%,#F3BF51_10%,#F1826F_15%,#EE6D83_19%,#D1E6F7_30%,#88AFD8_41%,#6589C5_53%,#4C4592_65%,#413581_77%,#3F2F70_89%,#412850_100%)]',
		text: 'text-white',
		column: 'bg-[#EAF2FBE0]',
		columnText: 'text-[#1B2540]',
		task: 'bg-[#8DB0DA]',
		taskText: 'text-[#14243A]',
		reminder: 'bg-[#F3BF51]',
	},
	{
		id: 'eva-01',
		bg: 'bg-gradient-to-br from-[#3A1D6E] to-[#1A0B2E]',
		text: 'text-[#8DC63F]',
		column: 'bg-[#1C1C1C]',
		columnText: 'text-[#8DC63F]',
		task: 'bg-[#8DC63F]',
		taskText: 'text-black',
		reminder: 'bg-[#F58220]',
	},
	{
		id: 'retro',
		bg: 'bg-[#DE6536]',
		text: 'text-black',
		column: 'bg-[#EFE8D2]',
		task: 'bg-[#F5B46C]',
		reminder: 'bg-[#F5B46C]',
	},
	{
		id: 'prado oscuro',
		bg: 'bg-[#001D21]',
		text: 'text-[#FAE9CF]',
		column: 'bg-[#DFE1CB]',
		task: 'bg-[#AEB17E]',
		taskText: 'text-black',
		columnText: 'text-[#001D21]',
	},
	{
		id: 'wolf',
		bg: 'bg-[#0C9B99]',
		text: 'text-white',
		column: 'bg-[#363f5b]',
		task: 'bg-[#EADCD9]',
		taskText: 'text-black',
		columnText: 'text-white',
		reminder: 'bg-[#E68B70]',
	},
	{
		id: 'grad-blink-1',
		bg: 'bg-gradient-to-b from-[#3d1a14] via-[#c84a1d] to-[#e8a87c]',
		text: 'text-[#FAE9CF]',
		column: 'bg-[#F6D2AC]',
		columnText: 'text-black',
		task: 'bg-[#e35e49c2]',
	},
	{
		id: 'grad-blink-4',
		bg: 'bg-gradient-to-b from-[#FA9009] via-[#95122A] to-[#150B09]',
		text: 'text-[#020817ff]',
		column: 'bg-[#020817ff]',
		columnText: 'text-[#FAE9CF]',
		task: 'bg-[#CD6242]',
	},
])

export const lightTheme: Theme = { ...themesList.filter((theme) => theme.id == 'retro')[0] }

export const darkTheme: Theme = { ...themesList.filter((theme) => theme.id == 'prado oscuro')[0] }
